spring:
  cloud:
    config:
      server:
        git:
          uri: https://Nikita_Novozhilov@bitbucket.org/Nikita_Novozhilov/netflix-oss-homework-settings.git
          clone-on-start: true

management:
  context-path: /manage
  endpoints:
    web:
      base-path: /manage