# docker-compose up -d
# docker-compose up <service-name>
# docker-compose stop

version: '3.7'

services:

  elk:
    image: sebp/elk:670
    container_name: elk_5601
    ports:
      #Kibana
      - "5601:5601"
      #Elasticsearch
      - "9200:9200"
      #Logstash
      - "5044:5044"
    volumes:
      - ./elk/input.conf:/etc/logstash/conf.d/02-beats-input.conf

  postgresql:
    image: postgres:11.2-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    env_file:
      - ./env/postgresql.env
    environment:
      - POSTGRES_DB=netflix_oss

  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: zookeeper
    ports:
     - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.12-2.2.0
    container_name: kafka
    ports:
      - "9092:9092"
    env_file:
      - ./env/kafka.env
    environment:
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_CREATE_TOPICS: "employees:1:1"
    depends_on:
      - zookeeper

  hystrix-dashboard:
    image: kennedyoliveira/hystrix-dashboard:1.5.6
    container_name: hystrix_7979
    ports:
      - "7979:7979"

  zipkin-dashboard:
    image: openzipkin/zipkin:2.12.8
    container_name: zipkin_9411
    ports:
      - "9411:9411"

  config-server:
    image: nikitanov/config-server:0.0.1
    container_name: config-server_8888
    restart: on-failure
    ports:
      - "8888:8080"
    env_file:
      - ./env/config-server.env
    environment:
      LOGGING_CONFIG: "/logback/logback-spring.xml"
      SERVER_PORT: 8080
      SERVER_NON_SECURE_PORT: 8888
    volumes:
      - ./logback/logback.xml:/logback/logback-spring.xml
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/manage/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  eureka:
    image: nikitanov/eureka-server:0.0.1
    container_name: eureka_8282
    restart: on-failure
    ports:
      - "8282:8080"
    env_file:
      - ./env/.env
      - ./env/eureka.env
    environment:
      LOGGING_CONFIG: "/logback/logback-spring.xml"
      SERVER_PORT: 8080
      SERVER_NON_SECURE_PORT: 8282
    volumes:
      - ./logback/logback.xml:/logback/logback-spring.xml
    depends_on:
      - config-server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/manage/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  workspaces_1:
    image: nikitanov/workspaces-api:0.0.1
    container_name: workspaces_9090
    restart: on-failure
    ports:
      - "9090:8080"
    env_file:
      - ./env/.env
      - ./env/workspaces.env
    environment:
      LOGGING_CONFIG: "/logback/logback-spring.xml"
      SERVER_PORT: 8080
      SERVER_NON_SECURE_PORT: 9090
    volumes:
      - ./logback/logback.xml:/logback/logback-spring.xml
    depends_on:
      - config-server
      - eureka

  workspaces_2:
    image: nikitanov/workspaces-api:0.0.1
    container_name: workspaces_9091
    restart: on-failure
    ports:
      - "9091:8080"
    env_file:
      - ./env/.env
      - ./env/workspaces.env
    environment:
      LOGGING_CONFIG: "/logback/logback-spring.xml"
      SERVER_PORT: 8080
      SERVER_NON_SECURE_PORT: 9091
    volumes:
      - ./logback/logback.xml:/logback/logback-spring.xml
    depends_on:
      - config-server
      - eureka

  employees:
    image: nikitanov/employees-api:0.0.1
    container_name: employees_9093
    restart: on-failure
    ports:
      - "9093:8080"
    env_file:
      - ./env/.env
      - ./env/employees.env
    environment:
      LOGGING_CONFIG: "/logback/logback-spring.xml"
      SERVER_PORT: 8080
      SERVER_NON_SECURE_PORT: 9093
    volumes:
      - /data/employees:/data/employees
      - ./logback/logback.xml:/logback/logback-spring.xml
    depends_on:
      - config-server
      - eureka

  gateway:
    image: nikitanov/api-gateway:0.0.1
    container_name: gateway_9094
    restart: on-failure
    ports:
      - "9094:8080"
    env_file:
      - ./env/.env
      - ./env/gateway.env
    environment:
      LOGGING_CONFIG: "/logback/logback-spring.xml"
      SERVER_PORT: 8080
      SERVER_NON_SECURE_PORT: 9094
    volumes:
      - ./logback/logback.xml:/logback/logback-spring.xml
    depends_on:
      - config-server
      - eureka
